### ISSUE TITLE
Support for HTTP/2 Push

### ISSUE THREAD

**Issue by ghost** [cbas/express-history-api-fallback#4]
I want to support HTTP/2 Server Push for my single-page application which requires adding some custom Link headers to the response along with the index.html file. Any suggestions on how to make this work with this middleware?

**Comment by sebdeckers** [comment]
🤔 I have not tried it myself but you could, in theory, pass `headers` to `res.sendFile` as follows:

``` js
import fallback from 'express-history-api-fallback'
import express from 'express'
const app = express()
const root = `${__dirname}/public`
app.use(express.static(root))
app.use(fallback('index.html', {
  root,
  headers: {
    'Link: <URL>; rel=preload'
  }
}))
```

Reference:
http://expressjs.com/en/api.html#res.sendFile
