### ISSUE TITLE
sendFile is undefined

### ISSUE THREAD

**Issue by tonyfleck76** [cbas/express-history-api-fallback#9]
For some reason sendFile is coming up undefined and this is throwing an error when trying the server attempts to reroute my requests for my vue app. I am not sure why it is undefined, as I am using node 4.14 so it seems that it should be working just fine. Any chance I'm missing something here?

**Comment by sebdeckers** [comment]
Oops, that's odd. 🙀 Got sample code?

**Comment by tonyfleck76** [comment]
Actually I just managed to stumble across the solution thanks to a lucky google search. Turns out it is sendfile instead of sendFile, and everything works just fine when I make this change. Of course, the Express documentation says it's sendFile so I don't really have a good explanation for what's going on.

**Comment by sebdeckers** [comment]
🤔 Which version of Express are you using?

**Comment by sebdeckers** [comment]
express@4 has res.sendFile http://expressjs.com/en/4x/api.html#res.sendFile
express@3 has res.sendfile http://expressjs.com/en/3x/api.html#res.sendfile
express@2 has res.sendfile http://expressjs.com/2x/guide.html#res.sendfile()

**Comment by tonyfleck76** [comment]
Oops, I wrote node 4.14 in my original post but I meant Express 4.14. On top of that previous error, it looks like I have express 4.14 installed globally, but 4.0 installed on this project. And sendFile wasn't introduced until 4.8 so I think that pretty much explains it. Looks like I still have a lot to learn about npm! Thanks for your help!

**Comment by tonyfleck76** [comment]
Just confirmed that once I upgraded express to 4.14 sendFile works just fine.

**Comment by sebdeckers** [comment]
TIL 💡 Let me see if I can do a quick patch for that.

Thanks for reporting the problem (& solution). 👍

**Comment by tonyfleck76** [comment]
No problem! Glad I could stumble across that! Haha

**Comment by sebdeckers** [comment]
@tonyfleck76 Could you give this patch a spin, please? `npm install sebdeckers/express-history-api-fallback`

**Comment by tonyfleck76** [comment]
Looks like it's working just fine, even with express 4.0!
